### ISSUE TITLE
LettuceConnectionFactory attempts plain-text connect to AWS Elasticache Redis

### ISSUE THREAD

**Issue by hanscrg** [spring-projects/spring-data-redis#2009]
We are running Spring Cloud Gateway with Spring Session. The session store is AWS Elasticache. The connection should be in SSL/TLS. We customized the ReactiveRedistConnectionFactory but not able to make connection with AWS Elastcache. Here is the customized Redis ReactiveRedisConnectionFactory with SSL enabled without cert verification,

        @Value("${spring.redis.host}")
	private String redisHost;

	@Value("${spring.redis.port}")
	private int redisPort;

	@Value("${spring.redis.password}")
	private String password;
        
        @Bean
	public ReactiveRedisConnectionFactory reactiveRedisConnectionFactory() {
			LettuceClientConfiguration lettuceClientConfiguration = LettuceClientConfiguration.builder().useSsl().disablePeerVerification().build();

			RedisStandaloneConfiguration redisStandaloneConfiguration = new RedisStandaloneConfiguration();

			redisStandaloneConfiguration.setHostName(redisHost);
			redisStandaloneConfiguration.setPort(redisPort);
			redisStandaloneConfiguration.setPassword(password);
		 
	        return new LettuceConnectionFactory(redisStandaloneConfiguration, lettuceClientConfiguration);
	    }

We just get exception as below,

17:56:21.280: [APP/PROC/WEB.0] Caused by: io.lettuce.core.RedisCommandTimeoutException: Command timed out after 1 minute(s)
17:56:21.280: [APP/PROC/WEB.0] 	at io.lettuce.core.ExceptionFactory.createTimeoutException(ExceptionFactory.java:51) ~[lettuce-core-5.3.3.RELEASE.jar:5.3.3.RELEASE]
17:56:21.280: [APP/PROC/WEB.0] 	at io.lettuce.core.protocol.CommandExpiryWriter.lambda$potentiallyExpire$0(CommandExpiryWriter.java:172) ~[lettuce-core-5.3.3.RELEASE.jar:5.3.3.RELEASE]
17:56:21.280: [APP/PROC/WEB.0] 	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[netty-common-4.1.51.Final.jar:4.1.51.Final]
...

The Redis Spring Boot Configuration:

```yaml
spring:
  redis:    
    host: ${host}
    port: ${port}
    ssl: true
    password: ${password}
    timeout: 60s      
  session:
    timeout: 7d
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: spring:session
```
------------------------------
Spring Boot: 2.3.3
Spring Cloud: Hoxton.SR7
