### ISSUE TITLE
Connection hangs forever using lettuce and timeouts are not working

### ISSUE THREAD

**Issue by KP-EV** [spring-projects/spring-data-redis#2863]
Hi,

we use spring-boot-starter-data-redis:3.2.2 with a single redis instance and configured these timeouts:

```
spring:
  data:
    redis:
      host: "${REDIS_HOST}" #ip address
      port: "6379"
      timeout: 150ms
      connect-timeout: 200ms
      lettuce:
        pool:
          enabled: true
          max-active: 3
          max-wait: 150ms
```

But we still notice that sometimes, after the application ran for a day, that the redis connection just completely dies and any call using @Cacheable annotation just hangs forever.

Looking into making the connection more reliable via this thread here: https://github.com/lettuce-io/lettuce-core/issues/1428

But iam also wondering why these three timeouts are not working and the connection still hangs forever. Any other call works fine and after a restart the application is working again.
